[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Player 1", email = "hyouseff227@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "asyncio>=4.0.0",
    "asyncpg>=0.32.0",
    "bcrypt>=5.0.0",
    "dotenvx>=0.0.0",
    "fastapi>=0.142.2",
    "pyjwt>=2.15.1",
    "python-dotenvx>=2.0.1",
    "python-json-logger>=4.2.0",
    "sqlalchemy[asyncio]>=2.1.4",
    "typing>=3.10.0.0",
    "uuid>=1.30",
]

[project.scripts]
ai-interactive-worksheet-app = "ai_interactive_worksheet_app:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
